### ISSUE TITLE
Make, and change a JSON in PHP

### ISSUE THREAD

**Issue by TheNeg0t1ator** [TheNeg0t1ator/Webtech2023Groep1#12]
just like fopen() XD

**Comment by CeyhanYildiz** [comment]
Ik zal hiervoor zorgen, maar ik heb meer informatie nodig over hoe de data wordt opgeslagen en wat het precies is.

**Comment by CeyhanYildiz** [comment]
Ik had geen idee hoe ik het databestand kon bekijken, en het spijt me dat ik het niet op tijd voor elkaar heb gekregen.

**Comment by CeyhanYildiz** [comment]
UPDATE: Ik heb de PHP-code geschreven, maar ik heb momenteel geen manier om het te testen. Ik ben niet bekend met de specifieke stappen om de code uit te voeren.
