### ISSUE TITLE
Push data from database to PHP file

### ISSUE THREAD

**Issue by TheNeg0t1ator** [TheNeg0t1ator/Webtech2023Groep1#13]
Extract data from database uppon PHP request

**Comment by CeyhanYildiz** [comment]
Ik zal hiervoor zorgen, maar ik heb meer informatie nodig over hoe de data wordt opgeslagen en wat het precies is. *3

**Comment by CeyhanYildiz** [comment]
Ik had geen idee hoe ik het databestand kon bekijken, en het spijt me dat ik het niet op tijd voor elkaar heb gekregen.

**Comment by CeyhanYildiz** [comment]
UPDATE: Ik heb de PHP-code geschreven. Het enige wat ik nog moet weten, is hoe het bestand van de PYNQ-Z2 heet van de temperatuur, zodat ik de gegevens kan ophalen. Trouwens, de gegevens worden niet naar PHP gestuurd; PHP haalt de gegevens op wanneer het geactiveerd wordt.
