### ISSUE TITLE
Get data from SQL database in PHP

### ISSUE THREAD

**Issue by TheNeg0t1ator** [TheNeg0t1ator/Webtech2023Groep1#14]

**Comment by CeyhanYildiz** [comment]
Ik zal hiervoor zorgen, maar ik heb meer informatie nodig over hoe de data wordt opgeslagen en wat het precies is. *2

**Comment by CeyhanYildiz** [comment]
Ik had geen idee hoe ik het databestand kon bekijken, en het spijt me dat ik het niet op tijd voor elkaar heb gekregen. *2
