### ISSUE TITLE
Basic Files toevoegen in de mappen

### ISSUE THREAD

**Issue by TheNeg0t1ator** [TheNeg0t1ator/Webtech2023Groep1#2]
hey, kunnen we de files die allemaal gaan nodig gaan hebben er in pushen, bv de js css html files?

**Comment by SamyWarnants** [comment]
de instructie files of gwn lege c en html files?

**Comment by TheNeg0t1ator** [comment]
Ja, simpele files, dat je een basis hebt om van te starten.
