### ISSUE TITLE
Use PHP

### ISSUE THREAD

**Issue by TheNeg0t1ator** [TheNeg0t1ator/Webtech2023Groep1#6]
make the site talk to the database using php and javascript.

**Comment by CeyhanYildiz** [comment]
Ik heb de PHP-code kunnen schrijven, maar helaas weet ik niet hoe ik deze code moet uitvoeren op onze server en/of  onze database.

**Comment by CeyhanYildiz** [comment]
Ik kon het PHP-gedeelte maken, het enige probleem is dat ik geen idee heb hoe ik de code moet uitvoeren. Ik was er niet bij in de vorige les en heb ook geen moeite gedaan om het na te vragen. Mijn excuses hiervoor.
